### ISSUE TITLE
BigInt Benchmarks vs Competitors

### ISSUE THREAD

**Issue by mgriebling** [leif-ibsen/BigInt#11]
I've been researching several of the BigInt implementations in terms of efficiency and thought I'd share my findings (if ok):

<img width="522" alt="Screenshot 2023-06-24 at 8 45 00 AM" src="https://github.com/leif-ibsen/BigInt/assets/2421348/70956d0d-6ef4-47ea-83dd-51ae31ad119e">

For the most part, your BigInt seems to win in a lot of areas and is close to the other packages otherwise. Overall, congratulations on your efforts and I would call your BigInt the winner and will likely be using it for the basis of a BigDecimal implementation. I know you've created an initial BigDecimal package and will be 
looking at that next.

Generally, a standard benchmark suite for comparing different Packages is missing. Here is my benchmark that I used which hopefully can be helpful to others:

```swift
//
//  BigInt1Tests.swift
//  BigIntPerformance
//
//  Created by Mike Griebling on 23.06.2023.
//

import BigInt

let name = "BigIntI"
let n2 = factorial(1000)
let n3 = factorial(100)

func factorial(_ n: Int) -> BInt {
    return (1 ... n).map { BInt($0) }.reduce(BInt(1), *)
}
let n1 = n2.description

func TimingBigInt1() {
 
  measure(name:"StringTo"+name) {
    let _ = BInt(n1)
  }
  
  measure(name:"StringFm"+name) {
    let _ = n2.description
  }
  
  measure(name:"Multiply"+name) {
    let _ = n2 * n2
  }
  
  measure(name:"Addition"+name) {
    let _ = n2 + n2
  }
  
  measure(name:"Division"+name) {
    let _ = n2 / n3
  }
  
  measure(name:"ANDing  "+name) {
    let _ = n2 & n3
  }
  
  measure(name:"ORing   "+name) {
    let _ = n2 | n3
  }
  
  measure(name:"ShiftLft"+name) {
    let _ = n2 << 100
  }
  
  measure(name:"ShiftRgt"+name) {
    let _ = n2 >> 100
  }
  
  measure(name:"Power   "+name) {
    let _ = n2 ** 20
  }
}
```

The timing function is pretty simple (from https://www.objc.io/blog/2018/06/14/quick-performance-timing/):

```swift
@discardableResult
func measure<A>(name: String = "", _ block: () -> A) -> A {
    let startTime = CACurrentMediaTime()
    let result = block()
    let timeElapsed = CACurrentMediaTime() - startTime
    print("Time: \(name) - \(String(format:"%1.10f", timeElapsed))")
    return result
}
```

**Comment by leif-ibsen** [comment]
Thanks for your effort comparing BigInt's.
I think your results look fine
