### ISSUE TITLE
Performance of expMod

### ISSUE THREAD

**Issue by wjamesjr** [leif-ibsen/BigInt#16]
I spend quite a bit of time on stackoverflow.com looking for ideas for big integer functions and optimizations.  Yesterday, I ran across the below post that was discussing the difference in powMod performance between Java and C# (about a 10x difference).  I was curious and did some timing comparison with BInt and Java.  I was surprised to find a 10 times difference between Java and BInt as well.

[](url)
https://stackoverflow.com/questions/71090461/why-is-the-biginteger-modpow-function-in-c-sharp-much-slower-than-that-in-java/71139746#71139746
[](url)

The code below is what I used for Java:

'''
package HelloWorld;

import java.math.BigInteger;

public class HelloWorld {

	public static void main(String[] args) {
		    BigInteger num = new BigInteger("444266014606582911577255360081280172978907874637194279031281180366057");
		    BigInteger m = new BigInteger("2");
		    BigInteger n = new BigInteger("3");
		    System.out.println("Start multiply.");
		    for (int i = 3; i <= 200000; i++)
		        m = m.multiply(BigInteger.valueOf(i));
		    System.out.println("Start mod pow.");
		    long startTime = System.currentTimeMillis();
		    n = n.modPow(m, num);
		    System.out.println(System.currentTimeMillis() - startTime);
		    System.out.println(n);
		    System.out.println("Done");

	}

}
'''

which outputs the following on my computer:

Start multiply.
Start mod pow.
301
268505793205609810380552624057853203943543333490886537812151593684645
Done

for BInt, I ran the below code:

'''

let ii = BInt.factorial(200000)
let jj = BInt("444266014606582911577255360081280172978907874637194279031281180366057")!
let three = BInt("3")!
print("starting expMod")
let methodStart = Date()
let kk = three.expMod(ii, jj)
var methodFinish = Date()
var et1 = methodFinish.timeIntervalSince(methodStart)
print(et1)
print(kk)
exit(0)

'''

My machine outputs the below for the Int code:

starting expMod
3.043316960334778
268505793205609810380552624057853203943543333490886537812151593684645

The answer is the same for both, however the BInt modExp is 10 time slower for this case.  Any idea why Java is so much faster (300 msec vs. 3 seconds) for this code?

**Comment by wjamesjr** [comment]
title should have been expMod.  Darn spell check

**Comment by leif-ibsen** [comment]
Will look into it

**Comment by leif-ibsen** [comment]
I ran your example and got almost the same results. 2.4 secs for BInt and 0.2 secs for Java.

I have looked into the BigInteger source code,
and see that it uses a (rather complicated looking) function called oddModPow,
which is obviously a better algorithm than the one I use.

I have my own performance comparisons between BInt and Java and for moderately sized exponents,
BInt is about half as fast as Java.

**Comment by wjamesjr** [comment]
Thanks for looking at it.  I looked at your code and the Java code.  Both have quite a bit of complexity.   I am using the expMod and division code out of your library and mating it to a floating point fft multiplication package that I have been using for years with C and Xojo.  I also have converted the real (excludes complex) portion of mpmath on the Python side to Swift to use for a floating point arbitrary precision capability.  What I like doing is number theory applications like binary splitting to compute constants like pi, e, catalan, euler and such along with computing big Bernoulli fractions of 1, 10 and higher million.  I also like to work with prime factorization code such as quadratic sieving.  What I found is prime factorization relies heavily on expMod for speed.  Most of my code were routines found in the Python world ported over to Swift.  I have been a little disappointed with speed though.  I have been getting performance better than plain Python but a bit less than pypy3.  I can factor an 80 digit number in about 4 hours, but cannot factor RSA 100 in a reasonable time (would take about 2 weeks on my Intel laptop (look forward to a M3 one).  If in the future you find possible speedups in the expMod or inverse routines it would be most appreciated.  I do not plan to publicly source my code as I have no desire for long term support.  However  if you would like a copy to use or test against it I would be happy to zip it up and send you a copy.

**Comment by leif-ibsen** [comment]
Thanks, please zip it and mail to 
   
   leif.m.ibsen@gmail.com
   
About expMod and modInverse performance,
please note that there are integer versions of both

  public func expMod(_ x: BInt, _ m: BInt) -> BInt
  public func expMod(_ x: BInt, _ m: Int) -> Int
  
  public func modInverse(_ m: BInt) -> BInt
  public func modInverse(_ m: Int) -> Int
  
The integer versions - if applicable - are many times faster than the BInt versions

**Comment by wjamesjr** [comment]
I mailed my library to you. 

I do use the Int versions, in fact I made some modifications to the non-Int versions to call the Int versions when the big integers were Int size.

**Comment by wjamesjr** [comment]
As an additional test I ran a test in Python:

`
import time
import math

m = 444266014606582911577255360081280172978907874637194279031281180366057
fact = math.factorial(200000)
time1 = time.time()
x = pow(3, fact, m)
time2 = time.time() - time1
print(x)
hr = int(time2 // 3600)
time2 = time2 - (hr * 3600)
my_min = int(time2 // 60)
sec = (time2 - (my_min * 60))
print("time elapsed ", hr, ":", my_min, ": %2.2f" % sec)
`

result:

268505793205609810380552624057853203943543333490886537812151593684645
time elapsed  0 : 0 : 1.65

I was surprised that Python was also twice as fast.  I think Python uses 4-bit m-ary algorithm but I am beginning to wonder if the performance issue is more general.  What if it is the base-case multiplies and divides?  How would we know where the worst slowdowns are?

**Comment by wjamesjr** [comment]
Just for grins I wanted to create a quick and dirty 8-bit m-ary expMod and see the time difference.  I tested the below code:

``
extension Array where Element == UInt {
    
    func toUInt8Array() -> [UInt8] {
        var sc = self.count
        if sc == 0 { return []}
        var arrOut: [UInt8] = []
        sc -= 1
        for iIndex in 0 ... sc {
            arrOut.append(UInt8(self[iIndex] & 0xff))
            arrOut.append(UInt8((self[iIndex] >> 8) & 0xff))
            arrOut.append(UInt8((self[iIndex] >> 16) & 0xff))
            arrOut.append(UInt8((self[iIndex] >> 24) & 0xff))
            arrOut.append(UInt8((self[iIndex] >> 32) & 0xff))
            arrOut.append(UInt8((self[iIndex] >> 40) & 0xff))
            arrOut.append(UInt8((self[iIndex] >> 48) & 0xff))
            arrOut.append(UInt8((self[iIndex] >> 56) & 0xff))
        }
        return arrOut
    }
}

func expMod8ary(_ base: APMInt,_ power: APMInt,_ m: APMInt) -> APMInt {
    let e = power.words.toUInt8Array()
    var g: [APMInt] = [APMInt.C1]
    for indx in 1 ... 255 {
        g.append((g[indx - 1] * base) % m)
    }
    var r: APMInt = g[Int(e[e.count - 1])]
    for indx in (0 ... (e.count - 2)).reversed() {
        for _ in 1 ... 8 {
            r = r.square() % m
        }
        r = (r * g[Int(e[indx])]) % m
    }
    return r
}

var i1: APMInt = APMInt()
var power = APMInt.factorial(200000)
var m: APMInt = "444266014606582911577255360081280172978907874637194279031281180366057"
timeit {
    i1 = expMod8ary(APMInt.C3, power, m)
}
print(i1)
exit(0)
``

with this output:

Elapsed time is 0000:00:00:08.680206
268505793205609810380552624057853203943543333490886537812151593684645

Over twice slower than your expMod.  I am still trying to figure out what this means.  It definitely shows that expMod is performing better than the above.  It did not however help me understand why Python and Java versions are faster.

**Comment by wjamesjr** [comment]
And comparison with one more algorithm, some base case modExp by squaring:

`
public func expModBySquaring(_ base: APMInt,_ power: APMInt, _ m: APMInt) -> APMInt {
    let powLen = power.bitWidth - 1
    var result = APMInt.C1
    var base = base
    for thisBit in 0 ... powLen {
        if power.bitGet(thisBit) == 1 {
            result = (result * base) % m
        }
        base = base.square() % m
    }
    return result
}
`

Completed in 11.4 seconds compared to 8-ary in 8.49 seconds and production modExp in 3 seconds.  I don't think the issue is with the production modExp algorithm but slowness in functions that modExp uses.  I don't have any ideas at this point on what to optimize or change.
