### ISSUE TITLE
Improvement to div128

### ISSUE THREAD

**Issue by wjamesjr** [leif-ibsen/BigInt#6]
I have been reviewing all the big integer libraries on GIthub.  Yours is maybe the only one that has incorporated algorithms beyond base cases.  I have been developing my own library and have incorporated a number of your algorithms.  In doing so I have found a couple of things that I would recommend.  This issue is the first.  I have a prime factoring function that does an intense number of small divides.  I was unhappy with the performance and when debugging I found that a large number of divides had the upper 64 bits of the dividend in div128 that are zero.  This came as a surprise and leads to an optimization that I include below.

`
    // [GRANLUND] - algorithm 4
    // (u1 || u0) / d => (q, r)
    static func div128(_ u1: UInt, _ u0: UInt, _ d: UInt, _ dReciprocal: UInt) -> (q: UInt, r: UInt) {
        assert(u1 < d)
        assert(d >= 0x8000000000000000)
        if u1 == 0 {
            let (q, r) = u0.quotientAndRemainder(dividingBy: d)
            return (q, r)
        }
        var  ovfl = false
        var (q1, q0) = dReciprocal.multipliedFullWidth(by: u1)
        (q0, ovfl) = q0.addingReportingOverflow(u0)
        (q1, _) = q1.addingReportingOverflow(u1)
        if ovfl {
            q1 &+= 1
        }
        q1 &+= 1
        var r = u0 &- q1 &* d
        if r > q0 {
            q1 &-= 1
            r &+= d
        }
        if r >= d {
            q1 += 1
            r -= d
        }
        return (q1, r)
    }
`

**Comment by wjamesjr** [comment]
messed up the code insertion.


  ```
  // [GRANLUND] - algorithm 4
    // (u1 || u0) / d => (q, r)
    static func div128(_ u1: UInt, _ u0: UInt, _ d: UInt, _ dReciprocal: UInt) -> (q: UInt, r: UInt) {
        assert(u1 < d)
        assert(d >= 0x8000000000000000)
        if u1 == 0 {
            let (q, r) = u0.quotientAndRemainder(dividingBy: d)
            return (q, r)
        }
        var  ovfl = false
        var (q1, q0) = dReciprocal.multipliedFullWidth(by: u1)
        (q0, ovfl) = q0.addingReportingOverflow(u0)
        (q1, _) = q1.addingReportingOverflow(u1)
        if ovfl {
            q1 &+= 1
        }
        q1 &+= 1
        var r = u0 &- q1 &* d
        if r > q0 {
            q1 &-= 1
            r &+= d
        }
        if r >= d {
            q1 += 1
            r -= d
        }
        return (q1, r)
    }

```

**Comment by leif-ibsen** [comment]
I have tried the suggested change, but haven’t seen any overall performance improvement

**Comment by wjamesjr** [comment]
I guess it depends on the applications involved.  I am working on a multi-core multiple polynomial quadratic sieve and the performance is driven by Mod and DIvMod.  I have looked hard and long at your division algorithms for performance improvements  and I have not found found anything significant yet.  Thanks for looking at it.
