### ISSUE TITLE
Failing assertion in fft code (Fermat init)

### ISSUE THREAD

**Issue by wjamesjr** [leif-ibsen/BigInt#7]
I have been using your ffttimes code to compare with floating point algorithms in my library.  In doing so I had issues with assertions failing in the Fermat Init.  At first I did not know what the problem was because I was running in release mode and just getting incorrect values.  It was only when I starting debugging that I saw that I had assertions each time it failed.  I really line your fft algorithm but have not been able to understand it completely.  I did try to figure out how to prevent the assertions, although it might not be the best kind of fix.  After I modded it, I have not been able to get a case where my routines and yours disagree.  It seems to be solid.  Below is how I changed the calculation of 'n'.

   ```
 // bw = product bitwidth
    init(_ bw: Int) {
        let logBw = 64 - bw.leadingZeroBitCount
        self.k = (logBw - 6) >> 1
        self.K = 1 << self.k
        self.m = 1 << (logBw - 6 - self.k)
        var n = (((2 << logBw) >> self.k + self.k) >> self.k + 1) << self.k
        n = (n / 64) * 64
        if n < (2 << logBw) >> self.k + self.k { n += 64}
        self.n = n
        var x = [UInt]([1])
        x.shiftLeft(self.n)
        x.bitSet(0)
        self.N = x
        self.theta = self.n >> self.k
        //assert(self.n >= (2 << logBw) >> self.k + self.k)
        //assert(self.n % self.K == 0)
        //assert(self.n % 64 == 0)
    }

```

**Comment by leif-ibsen** [comment]
Please provide an example, that is, two numbers where the algorithm computes the wrong product.
Thanks.

**Comment by wjamesjr** [comment]
I could not remember, so I created some new test code.  It fails with two numbers with the following number of limbs and self.n values:
limbs self.n
100     2064
101     2064
200     4112
300    4128
1000  8224
1023  8224

I don't believe it matters what the content is but I tested with all limbs == Uint.max, so the numbers were a multiple of 64-bits like the below:

    let u1: [UInt] = Array(repeating: UInt.max, count: i)

I believe the init will fail for all limb counts below 1024.  I realize that you start at higher limb counts in your library so for you it may not be an issue .  I created the workaround for me because I was testing at smaller values.

**Comment by leif-ibsen** [comment]
Thanks for your response. FFT multiplication is not used for multiplicands with fewer than 6000 limbs, 
because for smaller values ToomCook multiplication is faster.
For my FFT code to work, self.n must be divisible by 64 which means that self.k must be at least 6,
which it is by a large margin with the current Limb limit of 6000.
It's true that for a Limb width of 1024 it wouldn't work.
