### ISSUE TITLE
Getting error while building against generic device - "Integer literal '1307674368000' overflows when stored into 'Int'"

### ISSUE THREAD

**Issue by ashokjnvp** [leif-ibsen/BigInt#8]
Getting error while building against generic device - "Integer literal '1307674368000' overflows when stored into 'Int'"

**Comment by leif-ibsen** [comment]
The BigInt documentation states that "BigInt requires Swift 5.0. It also requires that the Int and UInt types be 64 bit types."
Your 'Int' type is a 32 bit type, which is why you get the error. BigInt can't be used when 'Int' is a 32 bit type
